name: yuvaan
description: Magical Maze!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_screenutil: 1.0.2
  animated_text_kit: 2.0.0
  drawing_animation: ^0.1.3
  carousel_slider: 1.4.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/past_sponsors_logo/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat-Black
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
          style: italic
    - family: Montserrat-Bold
      fonts:
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
    - family: Montserrat-ExtraBold
      fonts:
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
    - family: Montserrat-ExtraLight
      fonts:
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          style: italic
    - family: Montserrat-Light
      fonts:
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
          style: italic
    - family: Montserrat-Medium
      fonts:
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          style: italic
    - family: Montserrat-Regular
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
    - family: Montserrat-SemiBold
      fonts:
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
    - family: Montserrat-Thin
      fonts:
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
          style: italic
    - family: AveriaSansLibre-Bold
      fonts:
        - asset: fonts/Averia_Sans_Libre/AveriaSansLibre-Bold.ttf
        - asset: fonts/Averia_Sans_Libre/AveriaSansLibre-BoldItalic.ttf
          style: italic
    - family: AveriaSansLibre-Regular
      fonts:
        - asset: fonts/Averia_Sans_Libre/AveriaSansLibre-Regular.ttf
        - asset: fonts/Averia_Sans_Libre/AveriaSansLibre-Italic.ttf
          style: italic
    - family: Permanent Marker
      fonts:
        - asset: fonts/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Righteous
      fonts:
        - asset: fonts/Righteous/Righteous-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy/Satisfy-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
